# NumPy Tutorial

NumPy is one of the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. In this tutorial we will be covering some of the basic concepts in numpy such as arrays and its operations, a few mathematical functions, and sampling random numbers from some widely used probability distributions.

You can find the documentation for the latest stable NumPy version [here](https://numpy.org/doc/stable/), and more resources for learning NumPy [here](https://numpy.org/learn/).

## NumPy Overview

In [5]:
# Do you know which version of numpy are you using?
# Why is it important to know that? Answer it yourself with the reason.: To know which features are available and stuff like that.(Actually while setting up, i couldnt get it to work initially becuase i had the wrong version lol)

import numpy as np
print(np.__version__)

2.2.0


In [6]:
# Is it necessary to always use "np" as an alias for numpy? Uncomment the line below and check it out: Nope

import numpy as a
print(a.array([1]))

[1]


## Arrays

NumPy works with "multidimensional homogeneous arrays", which are
multidimensional tensors containing elements of the same data type.

Two dimensional arrays are similar to matrices that we are familiar with,
whereas higher dimensional arrays are analogous to tensors from linear algebra.

In [7]:
# You can create a numpy array using an iterable (eg: lists, tuples)

arr1 = np.array([1,2,3,4,5])                # Using a list
arr2 = np.array((5,6,7,8), dtype=float)     # Using a tuple (data type float)
arr3 = np.array(range(4))                   # Using a 'range' object
arr4 = np.array([[1,2],[3,4]])              # Using a list of lists to create a 2D array
print(arr1, arr2, arr3,"\n-----")
print(arr4,"\n-----")

# NumPy also has inbuilt functions to create arrays
arr5 = np.arange(6)
print(arr5)

[1 2 3 4 5] [5. 6. 7. 8.] [0 1 2 3] 
-----
[[1 2]
 [3 4]] 
-----
[0 1 2 3 4 5]


In [20]:
# Q: Can you create arrays of non numerial types? Like strings? Try it!: Yes we can
arr= np.array(["a","b","c"])
print(arr.dtype)
print(type(arr[0]))
# If you can, what can you do with such arrays?: For them I think there won't be any significant advantage over simple lists.

# Q: Can you create an array of mixed types? Try it! WHat happens to the elements of the array?
# Ans: Kindof, as syntax we can write it, **but in the array they get stored in the same datatype**. (All elements got converted to string datatype in my trial)
ar=np.array(["a", 69, 4.2])
print(ar)
ar=np.array([4.2,int(69),int(19)]) #here all are stored as float in the array
print(ar)
print(ar.dtype) #I searched online for this command...it clearly shows that numpy array stores all data in one single datatype only
print(type(ar[0]))
# What can you conclude from this?

['a' 'b' 'c']
<U1
<class 'numpy.str_'>
['a' '69' '4.2']
[ 4.2 69.  19. ]
float64
<class 'numpy.float64'>


In [22]:
# Remember, everything in python is an object, which means that the numpy array
# is also an object. You can see what type of object it is by using the
# type() function
ass=np.array([1,2,3])
ars=np.array([1.2,2.3,3.4])
arr=np.array(["a","b"])
print(type(ass))
print(type(ars))
print(type(arr))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
# numpy.ndarray is a homogeneous array, which means every array has a
# particular data type. What datatype does "arr1" have?
arr1.dtype

dtype('int64')

In [25]:
# You can check the number of dimensions of a numpy array by using the "shape" attribute of the array
arr4.shape
ar = np.array([1,2,3])
ass=np.array([[1,2,3,3],[1,2,4,5]])
print(ar.shape, ass.shape)

(3,) (2, 4)


In [30]:
# You can change the shape of an array using the "reshape" method.
arr6 = arr5.reshape(3,2)
print(arr6)
print()
ars=ass.reshape(4,2)
print(ars)
ass=ass.reshape(2,4)
# NOTE: ars=ass.reshape(4,1) gives error as expected. While reshaping, size should remain same.

[[0 1]
 [2 3]
 [4 5]]

[[1 2]
 [3 3]
 [1 2]
 [4 5]]


In [32]:
# Note that the default behaviour of 'reshape' is to arrange the values row-wise
# It is also possible to arrange the values column-wise as well
arr6 = arr5.reshape(3,2,order='F')
print(arr6)
print()
ass=ass.reshape(2,4,order='F')
print(ass) #remains same as expected, nice

[[0 3]
 [1 4]
 [2 5]]

[[1 2 3 3]
 [1 2 4 5]]


In [39]:
# What's the easiest way to create an array with shape (2,5) that returns
# the same array as the statement below? (Hint: Use the "numpy.arange" function)
#np.array([[1,2,3,4,5],[6,7,8,9,10]])

# Write code below:
qa=np.arange(1, 11, 1) # np.arange(first number, 1 more than last number, step size)
qa=qa.reshape(2,5)
print(qa)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
# numpy has some convenient functions to create certain special arrays ...
# How would you create a numpy array with shape (3,10) that contains all 0's?
# Write code below:
qa=np.zeros(30, dtype=np.int64) #similarly np.ones() also exists
#np.empty(2) creates array with 2 random values. 
#np.linspace(start value, end value, number of items) creates an array with equally spaced elements, such that first element=start value, last element=end value and number of elements=no. of items.
qa=qa.reshape(3,10)
print(qa)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [44]:
# A very useful function to create a special array ... 

# numpy.linspace is a function provided by the NumPy library that generates 
# an array of evenly spaced numbers over a specified interval. It is particularly useful 
# for creating numerical sequences for simulations, visualizations, and other applications 
# that require regularly spaced intervals.

start = 0.01
stop = 0.89
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#endpoint = true means stop included otherwise excluded
#retstep if true, step size is also returned
#dtype is used to specify datatype, if None written, then it is automatically inferred from the input


array([0.01      , 0.02795918, 0.04591837, 0.06387755, 0.08183673,
       0.09979592, 0.1177551 , 0.13571429, 0.15367347, 0.17163265,
       0.18959184, 0.20755102, 0.2255102 , 0.24346939, 0.26142857,
       0.27938776, 0.29734694, 0.31530612, 0.33326531, 0.35122449,
       0.36918367, 0.38714286, 0.40510204, 0.42306122, 0.44102041,
       0.45897959, 0.47693878, 0.49489796, 0.51285714, 0.53081633,
       0.54877551, 0.56673469, 0.58469388, 0.60265306, 0.62061224,
       0.63857143, 0.65653061, 0.6744898 , 0.69244898, 0.71040816,
       0.72836735, 0.74632653, 0.76428571, 0.7822449 , 0.80020408,
       0.81816327, 0.83612245, 0.85408163, 0.87204082, 0.89      ])

### Slicing arrays

In [13]:
# Akin to a regular list, we can slice numpy arrays as well, in various ways
# Note that indexing starts at 0 and not 1, and that the last index is not included

print(arr1)
print(arr1[0:5])
print(arr1[0:4])
print(arr1[0:4:1]) #array[start:stop:step], start: starts slicing at start(start inclusive), stop:stops slicing at stop(stop exclusive), step: moves this much at a time
print(arr1[0:4:2])
print(arr1[::-1]) #If not specified, start defaults to the end of the array when the step is negative.

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4]
[1 2 3 4]
[1 3]
[5 4 3 2 1]


In [14]:
# Unlike regular lists, we can slice multi-dimensional arrays as well
arr = np.arange(36).reshape(6,6)
print(arr)
print(arr[1:4,2:5])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 8  9 10]
 [14 15 16]
 [20 21 22]]


### Copies


In [15]:
# What happens when you assign an array to a new variable?

arr = np.arange(6)
print(arr)

new_arr = arr
print(new_arr)

new_arr[2] = 100          # Here we are changing a value in new_arr only,  but ...

print(arr)
print(new_arr)

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[  0   1 100   3   4   5]
[  0   1 100   3   4   5]


In [16]:
# Why did "arr" also change when only new_arr was changed?
# Because "new_arr = arr" was execcuted, the pointer to the array object that
# "arr" contains, was also assigned to "new_arr"

# To create a new copy of the array, use the "copy()" method
arr = np.arange(6)
new_arr = arr.copy()

new_arr[2] = 100          #changing new_arr but not changing arr
print(arr, new_arr)

[0 1 2 3 4 5] [  0   1 100   3   4   5]


## Mathematical Operations

In [17]:
# You can calculate the sum of all the elements in an array using np.sum()
print(np.sum(arr1))

15


In [18]:
# The numpy.ndarray object has many methods (member functions).
# Another way to calculate the sum of an array using one of these methods.
print(arr1.sum())

15


In [19]:
# There are many aggregate operations you can run on numpy arrays other than
# the sum() method.

print(arr1.mean()) #calculate mean
print(arr1.std()) #calculate standard deviation


3.0
1.4142135623730951


In [20]:
# Let's now calculate the minimum and the maximum values

print(arr1.min())
print(arr1.max())

1
5


In [21]:
# All basic operators like +,-,*,/ perform element-wise operations
# when dealing with arrays of the same shape
arr = np.arange(4)
print(arr, arr*arr)

[0 1 2 3] [0 1 4 9]


In [50]:
# How to obtain an array that has the squares of each element in "arr"?
# Type code below:
arr=np.arange(4)
ars=arr*arr
print(ars)
print(arr)

[0 1 4 9]
[0 1 2 3]


In [23]:
# In the case of multi-dimensional arrays, the above functions can take an additional parameter 'axis'
# to define the dimension along which the operation is to be performed. For example
arr = np.arange(36).reshape(6,6)
print(arr,"\n-----")

print(arr.sum(axis=0),"\n-----")    #sum of each column
print(arr.sum(axis=1))              #sum of each row

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 
-----
[ 90  96 102 108 114 120] 
-----
[ 15  51  87 123 159 195]


## Vector and Matrix operations

You can calculate the dot product between two vectors using `numpy.dot()`.

In [24]:
arr1 = np.arange(4)
arr2 = arr1 + 3
print(arr1)
print(arr2)

print(np.dot(arr1, arr2))

[0 1 2 3]
[3 4 5 6]
32


What happens when you run `numpy.dot()` on 2 matrices?

In [25]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.ones((2,3))
print(arr1,"\n-----")
print(arr2,"\n-----")

# The following lines are all equivalent, they all calculate the dot product of the two arrays
print(np.dot(arr1,arr2),"\n-----")
print(arr1.dot(arr2),"\n-----")
print(arr1 @ arr2)

[[0 1]
 [2 3]
 [4 5]] 
-----
[[1. 1. 1.]
 [1. 1. 1.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]] 
-----
[[1. 1. 1.]
 [5. 5. 5.]
 [9. 9. 9.]]


In [26]:
# What happens when the following code is run?
arr1 = np.arange(6).reshape(2,3)
arr2 = np.arange(12).reshape(4,3)
print(arr1,"\n-----")
print(arr2,"\n-----")
print(arr1 @ arr2) #matrix multiplication of 2X3 with 4X3 is not possible so it gives value error

[[0 1 2]
 [3 4 5]] 
-----
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 
-----


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [52]:
# As you might have guessed, the matrix dimensions are not conducive for matrix multiplication
# One has to often 'transpose' a matrix prior to carrying out operations like multiplication
# This can be done by a method `.T` as shown below
# We can also use the `np.transpose()` function to acheive the same result
arr1 = np.arange(6).reshape(2,3)
arr2=np.arange(12).reshape(4,3)
print(arr1,"\n-----")       # 2 x 3 matrix
print(arr2.T,"\n-----")     # 3 x 4 matrix
print(arr1 @ arr2.T,"\n-----")          # Now there will be no error
print(arr1 @ np.transpose(arr2))        # Same effect as the above statement

[[0 1 2]
 [3 4 5]] 
-----
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]] 
-----
[[  5  14  23  32]
 [ 14  50  86 122]] 
-----
[[  5  14  23  32]
 [ 14  50  86 122]]


In [53]:
# Let's look into some standard operations that can be performed on square matrices. 
# You can obtain the determinant of a square matrix by using the `np.linalg.det()` function

arr1 = np.arange(9).reshape(3,3)
print(arr1,"\n-----")
print(np.linalg.det(arr1))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
-----
0.0


In [54]:
# You can use the `np.linalg.inv()` function to calculate the inverse of a
# square matrix. What will happen when you run the following code? #it will give error, as inverse of arr1 does not exist as it is a singular matrix

print(np.linalg.inv(arr1))

LinAlgError: Singular matrix

In [57]:
# Q: What changes will you make to the above matrix to make it invertible?
# Try it out here ... #just do anything that changes the matrix such that its det is non zero. A matrix with all elements square of this matrix will work.
arr1=arr1*arr1
print(np.linalg.det(arr1))
print(np.linalg.inv(arr1))

# What do you think will be the output if we try finding a determinant and 
# inverse for a rectangular matrix? Do try it out. #wont work, they are defined only for square matrices
# Write code here:
ass=np.arange(6).reshape(2,3)
print(np.linalg.inv(ass))

-17950603746815.96
[[ 6.41963791e-02 -8.12792628e-05  9.12871301e-07]
 [-3.04181794e-02  2.39536064e-05 -9.35687748e-08]
 [ 4.02507101e-03 -9.35687748e-08  3.65503027e-10]]


LinAlgError: Last 2 dimensions of the array must be square

In [59]:
# Now let's find out the eigen values and vectors of the matrix

mat = np.arange(1,10).reshape(3,3)
print(mat)
eigen_value, eigen_vector = np.linalg.eig(mat)

print(f"Eigen values are {eigen_value}")
print(f"Eigen vectors are \n {eigen_vector}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Eigen values are [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen vectors are 
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Broadcasting arrays
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [9]:
# Let's see what happens when we multiply a 2D array with
# 1) a scalar
# 2) a 2D array with the same shape

arr = np.arange(9).reshape(3,3)
print(arr,"\n-----")

print(arr*2,"\n-----")  # Scalar multiplication
print(arr*arr)          # Element-wise multiplication

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
-----
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]] 
-----
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


In [10]:
# The scalar multiplication is as expected, and the array multiplication
# is element-wise, which is also expected. 
# What would happen when the above array is multiplied with a 1D array?
arr = np.arange(9).reshape(3,3)
arr2 = np.arange(3)
print(arr,"\n-----")
print(arr2,"\n-----")

print(arr2*arr) #when we write straightforward multiplication like this then each corresponding element of the two matrices is multiplied...if dimensions are different then broadcasting takes place and then they are multiplied

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
-----
[0 1 2] 
-----
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


What happened here?! To meaningfully perform multiplication, "arr2" is
transformed (broadcasted) into another array of shape (3,3), after which
element wise multiplication is performed. There are 2 rules for broadcasting:
1. Identify the array with smaller dimension and increase the dimension
  (by prepending "1" to the shape) such that it matches the dimension of the
  other array.
2. Identify arrays of size "1" along a dimension and increase the size along
   that dimension so that it matches the other array.

In the above example, the shape of arr2
changed as follows: `(3,) -> (1,3) -> (3,3)`
following which element-wise multiplication took place.

In [11]:
# Try to figure out what happens in the following example
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(4)
print(arr1,"\n-----")
print(arr2,"\n-----")

print(arr1+arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
-----
[0 1 2 3] 
-----
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]


In [12]:
# Can you explain why the following code throws an error? They can't be broadcasted together
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(3)
print(arr1,"\n-----")
print(arr2,"\n-----")
print(arr1+arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
-----
[0 1 2] 
-----


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

**You can read more about broadcasting in the [documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html)**.

## Comparison Functions

In [15]:
# Say you want to check whether a numpy array contains any number greater
# than 5. Would a regular python-styled comparison work?
arr = np.arange(8)
if arr > 5:
  print("True")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# It didn't work! But why didn't it?
# Let's try to understand what the > operator does
arr > 5

In [16]:
# The > operator, like any other comparison operator in numpy, return a boolean
# array of the same size. To check if any number in the array is greater than 5
# use numpy.any().
np.any(arr > 5)

np.True_

In [17]:
# To check if all the numbers in the array are greater than 5, you can use
# numpy.all()
np.all(arr > 5)

np.False_

In [18]:
# What if you want to see which elements in arr are greater than 5?
# You can use the boolean array as an index to index the original array!
print(arr)
print(arr>5) #creates a boolean array where each element is True if the condition arr > 5 is met, and False otherwise
print(arr[arr > 5]) #boolean indexing is used to select only the elements where the condition arr > 5 is True

[0 1 2 3 4 5 6 7]
[False False False False False False  True  True]
[6 7]


In [19]:
# Say you want to create a new array arr2 which has the same size as arr,
# but all the elements less than or equal to 5 are replaced by 5. How would
# you create such an array? (Hint: can you assigned values to indexed arrays?)

# Write code here:
arr2=arr.copy()
arr2[arr2<5]=5
print(arr2)

[5 5 5 5 5 5 6 7]


## Constants

In [20]:
# A number of oft used constants are defined in the numpy package
# These include numpy.inf, numpy.e, numpy.pi

print(np.inf, np.e, np.pi)

# numpy constants are documented at: https://numpy.org/doc/stable/reference/constants.html

inf 2.718281828459045 3.141592653589793


## Random Number Generation
Random numbers generation is an important tool in data science. 
It is used to generate random events during simulations
For example, the data sets that you have used in exercises E2 were created 
using controlled random number generation!

In [27]:
# Let's check how to generate 5 random numbers between 0 and 1

rg = np.random.default_rng()
print(rg.random(5))
print()

# Did you observe that everytime you run this cell, you get 5 different numbers.
#   Can you keep it to be a constant? We will try it out in the next cell

# For now, Can you try to generate a 2D random array?
# Write your code here
print(rg.random((3,4)))


[0.79571115 0.77490983 0.77741138 0.89814018 0.04733814]

[[0.20934134 0.47547876 0.34540851 0.40339127]
 [0.30892046 0.45116605 0.61985921 0.88718715]
 [0.70315137 0.12841811 0.06149953 0.79090826]]


In [33]:
# Run this cell multiple times and you will see the numbers in the array are always constant
# What is the reason for this? It is because we have provided a 'seed' value of 42

# Providing a seed value allows you to reproduce the same random numbers, which helps to 
# repeat, verify and validate simulations and experiments

rg = np.random.default_rng(42)
print(rg.random(5))

# Now change the seed and re-run the cell, you will find a different set of numbers repeating ...
rg = np.random.default_rng(56)
print(rg.random(5))

# Review the documentation at https://numpy.org/doc/stable/reference/random/generator.html 

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.72612605 0.01690281 0.98080107 0.72460421 0.54421216]


In [46]:
# The above statements create random numbers between 0 and 1. What if we want integers?

rg = np.random.default_rng(42)
print(rg.integers(22)) #when only when number passed, then it is interpreted as upper bound and lower bound is taken as 0 by default

# Now can you generate 5 random integers using rg.integers()? 
print(rg.integers(0,100,5))
# Try it yourself by referring to the documentation for numpy.random.default_rng().integers()
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html 

# Further, how will you generate a 3 x 5 matrix of random integers between 0 and 45?
print(rg.integers(0,45,(3,5)))
# Write your code here ...

1
[77 65 43 43 85]
[[ 3 31  9  4 23]
 [43 33 34 32 35]
 [23  5 37 20 22]]


## File operations using numpy

In [47]:
# you can save a numpy array to a file

arr = np.arange(12).reshape(6,2,order='F')
print(arr)
np.savetxt("numpy-array.csv", arr, delimiter=',',fmt='%.4f',newline='\n', header='y,x', footer='', comments='', encoding=None)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [48]:
# Read back the array from the file and print it
new_arr = np.loadtxt("numpy-array.csv", delimiter=',', skiprows=1, comments='#', encoding=None)
print(new_arr)

[[ 0.  6.]
 [ 1.  7.]
 [ 2.  8.]
 [ 3.  9.]
 [ 4. 10.]
 [ 5. 11.]]


In [ ]:
# Multiple numpy arrays can be compressed and written to a binary file using the "np.savez" function
# Data written in this way can be read back using the "np.load" function
# Refer to the documentation at 
#   https://numpy.org/doc/stable/reference/generated/numpy.savez.html and
#   https://numpy.org/doc/stable/reference/generated/numpy.load.html

### That's it ...

In [ ]:
# This unit has introduced the basics of numpy and numpy arrays.
# The functionality covered in this unit is sufficient to start using numpy for data analysis.
# We will start solving problems using these concepts and functions ...

# The numpy package has many more sub modules, functions and methods.
# Definitely visit the following links:

# Quickstart guide to numpy: https://numpy.org/doc/stable/user/quickstart.html
# Reference guide to all the numpy classes and methods: https://numpy.org/doc/stable/reference/index.html
# You can refer to the entire numpy documentation at https://numpy.org/doc/stable/index.html 

# There is much more to be 'discovered' in numpy, as it will be in almost all the Python libraries!
# Have fun!